dbt_project:
  outputs:
    dev:
      dbname: postgres
      host: database
      pass: Password
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: admin
  target: dev
