{
 "title": "Status Dashboard",
 "time": { "from": "now-1y/y", "to": "now-1y/y" },
 "panels": [
  {
   "title": "Issue Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('month', created_date) AS month,     SUM(issues_created) AS total_issues_created,     SUM(issues_closed) AS total_issues_closed,     SUM(issues_open) AS total_issues_open FROM public.fct_issue_distribution GROUP BY month ORDER BY month"
    }
   ]
  },
  {
   "title": "Issue Label Top 5",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT     count(*) as issue_count,     case when label_name is null then 'No label' else label_name end FROM public.fct_issue_distribution group BY label_name order by 1 desc limit 5"
    }
   ]
  },
  {
   "title": "Top 5 activities per repo (previous year)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT         repository,         SUM(total_commits + total_pull_requests + merged_pull_requests) AS total_activities,         SUM(total_commits) AS total_commits,         SUM(total_pull_requests) AS total_pull_requests,         SUM(merged_pull_requests) AS total_mergeed_pull_requests     FROM         public.fct_repository_activity     WHERE         EXTRACT(YEAR FROM month) = 2024  \nGROUP BY         repository     ORDER BY         total_activities DESC     LIMIT 5"
    }
   ]
  },
  {
   "title": "Top 3 Repository_activity(previous year)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH top_repos AS (     SELECT         repository,         SUM(total_commits + total_pull_requests + merged_pull_requests) AS total_activities     FROM         public.fct_repository_activity     WHERE         EXTRACT(YEAR FROM month) = 2024      GROUP BY         repository     ORDER BY         total_activities DESC     LIMIT 3 )  \nSELECT     fa.month AS \"time\",     COALESCE(SUM(CASE WHEN fa.repository = tr1.repository THEN fa.total_commits + fa.total_pull_requests + fa.merged_pull_requests END), 0) AS top1_repository,     COALESCE(SUM(CASE WHEN fa.repository = tr2.repository THEN fa.total_commits + fa.total_pull_requests + fa.merged_pull_requests END), 0) AS top2_repository,     COALESCE(SUM(CASE WHEN fa.repository = tr3.repository THEN fa.total_commits + fa.total_pull_requests + fa.merged_pull_requests END), 0) AS top3_repository FROM     public.fct_repository_activity fa CROSS JOIN     (SELECT repository FROM top_repos ORDER BY total_activities DESC LIMIT 1 OFFSET 0) tr1,     (SELECT repository FROM top_repos ORDER BY total_activities DESC LIMIT 1 OFFSET 1) tr2,     (SELECT repository FROM top_repos ORDER BY total_activities DESC LIMIT 1 OFFSET 2) tr3 WHERE     fa.repository IN (SELECT repository FROM top_repos)     AND EXTRACT(YEAR FROM fa.month) = 2024 GROUP BY     fa.month ORDER BY     fa.month"
    }
   ]
  },
  {
   "title": "Project cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT     month AS \"time\",     total_cost,     codex_cost,     waku_cost,     communication_cost,     infra_cost,     other_cost FROM public.fct_project_cost ORDER BY month"
    }
   ]
  }
 ]
}